### ISSUE TITLE
C++ import error

### ISSUE THREAD

**Issue by ludaavics** [rapidfuzz/python-Levenshtein#2]
On ubuntu 20.04, trying to import the package leads to the following error:

```
>>> import Levenshtein
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ltiako/miniconda3/envs/tmp-env/lib/python3.9/site-packages/Levenshtein/__init__.py", line 21, in <module>
    import rapidfuzz.distance.Levenshtein as _Levenshtein
  File "/home/ltiako/miniconda3/envs/tmp-env/lib/python3.9/site-packages/rapidfuzz/__init__.py", line 8, in <module>
    from rapidfuzz import distance, fuzz, process, string_metric, utils
  File "/home/ltiako/miniconda3/envs/tmp-env/lib/python3.9/site-packages/rapidfuzz/process.py", line 9, in <module>
    extract = _fallback_import(_mod, "extract")
  File "/home/ltiako/miniconda3/envs/tmp-env/lib/python3.9/site-packages/rapidfuzz/_utils.py", line 71, in fallback_import
    cpp_mod = importlib.import_module(module + "_cpp")
  File "/home/ltiako/miniconda3/envs/tmp-env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ltiako/miniconda3/envs/tmp-env/lib/python3.9/site-packages/rapidfuzz/process_cpp.py", line 9, in <module>
    from rapidfuzz.process_cpp_impl import FLOAT32 as _FLOAT32
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/ltiako/miniconda3/envs/tmp-env/lib/python3.9/site-packages/rapidfuzz/process_cpp_impl.cpython-39-x86_64-linux-gnu.so)
```

Googling a bit, i can fix using [ths](https://github.com/lhelontra/tensorflow-on-arm/issues/13#issuecomment-489296444), but it requires sudo acccess which is not always an option. And even when it is, it seems ideally this should work out of the box.

**Comment by maxbachmann** [comment]
Did you install `Levenshtein` from conda or from PyPI.

**Comment by ludaavics** [comment]
Conda

**Comment by maxbachmann** [comment]
Could you test whether the same issue occurs for the version on PyPI? Just to ensure this is an issue with the way we compile on conda

**Comment by maxbachmann** [comment]
@ngam @BastianZim @chrisburr @henryiii from the error message it appears I am building against a to new version of libstdc++ in https://github.com/conda-forge/rapidfuzz-feedstock. Does anyone of you know how this can be fixed in the conda forge build?

**Comment by ludaavics** [comment]
@maxbachmann 

having a bit of a hard time replicating, to be honest:
 - if I `conda install levenshtein` from a brand new (miniconda) environment, it works fine
 - if I conda install from a fresh copy of my prod environment, I get the error above
 - if I pip install from a fresh copy of my prod environment, it works fine
 - if i add levenshtein to my prod `environment.yaml` file and create a fresh environment from that, it works fine

So it looks like it might be some sort of dependency conflict? :shrug:

**Comment by ngam** [comment]
> * if I conda install from a fresh copy of my prod environment, I get the error above

Can you print `conda list` and `conda info` when this happens?

**Comment by ludaavics** [comment]
Unfortunately it's all private dependencies.
I am not familiar with conda at all... is there a way to see a dependency tree? If i can figure out which of our private package also relies on whatever `libstdc++.so.6` is, perhaps i can list its public dependencies?

**Comment by BastianZim** [comment]
I would guess that that is probably the problem. Because your private dependencies are most likely compiled in a different way, incompatibilities can arise. 

For the dependency tree, if you install mamba (`conda install mamba`) you can run `mamba repoquery whoneeds package_name --tree` and it will give you an output. Alternatively, `mamba repoquery depends package_name --tree` will give you the inverse.

**Comment by ngam** [comment]
Well, nobody from conda-forge will likely be able to help you effectively in this case...
1) we usually could only really help if you get everything from conda-forge
2) we usually cannot really help with private or closed-source stuff

**Comment by BastianZim** [comment]
Also, what @ngam said is unfortunately the case. It would probably be better if you consult with whoever creates your internal software. One thing to try though is setting the channel order and making sure that as much as possible is installed from conda-forge.

Run:

1. `conda config --add channels conda-forge`
2. `conda config --set channel_priority strict`
3. `conda update --all`

You have already added the conda-forge channel but this will make sure that it is at the top and preferred for packages.

**Comment by ludaavics** [comment]
For all practical purposes I'm all set, thanks to the fix mentioned in the original post. I just wanted to flag it to you guys / do what i can to help track down the issue.

If you are confident it must be an issue on our side, I'm happy with closing the issue. On the other hand if you think it's worthwhile to keep investigating -- e.g. to try and handle the conflict at install time -- I'm happy to keep experimenting with my setup under you guidance. Let me know what you prefer. 
To be clear, I totally understand if you have bigger fishes to fry!

Thanks for the tip on the dependency tree!

**Comment by BastianZim** [comment]
From the conda-forge side: We only really can fix issues that occur in environments that are only dependent on conda-forge packaged dependencies. We can try checking for obvious errors like above but besides that, the number of possible issues is too large to make a meaningful guess, unfortunately. 
The conda-forge compilers are in here, maybe they can help you? https://github.com/conda-forge/ctng-compilers-feedstock

**Comment by maxbachmann** [comment]
From the comments it does not appear to be possible to fix/improve this in this project, since I am simply using whatever build chain conda-forge provides me. So if someone would want to change this, it would need to be done in the conda-forge build chain itself. For this reason I will close the issue here.

Thanks @BastianZim and @ngam for your help investigating this.

**Comment by ngam** [comment]
Yeah, it is difficult as @BastianZim explains. I will just add one little note: You could build your own private projects with our tools and then things should be relatively easy to investigate. Everything we do in the conda-forge project could be done easily privately and locally, and everything is available in the open (docker images, toolchains, etc.). I believe it is very straightforward to make your projects "conda-forge"-compatible by relying on our available tools. Best of luck and sorry we cannot be of much help here. 

Thanks @maxbachmann four your patience!
