### ISSUE TITLE
matching_blocks returns a = 0 and b = 0 when I think it should be b = 2

### ISSUE THREAD

**Issue by kpm** [rapidfuzz/python-Levenshtein#3]
Hi, I'm trying out Levenshtein library.  I installed it using `pip install Levenshtein`.  I'm getting MatchingBlock(a=0, b=0, size=38), returned, when I think it should be returning MatchingBlock(a=0, b=2, size=38).  Difflib returns b = 2.  See the ipython transcript below, Thanks!

```

In [5]: a = "I for one welcome our new AI overlords"

In [7]: b= "> I for one welcome our new AI overlords\nyes I do too"

In [8]: Levenshtein.matching_blocks([],a,b)
Out[8]: [MatchingBlock(a=0, b=0, size=38), MatchingBlock(a=38, b=53, size=0)]

In [9]: len(a)
Out[9]: 38

In [10]: b= "> I for one welcome our new AI overlords\nyes I welcome them too"

In [11]: Levenshtein.matching_blocks([],a,b)
Out[11]: [MatchingBlock(a=0, b=0, size=38), MatchingBlock(a=38, b=63, size=0)]

In [12]: b= "x I for one welcome our new AI overlords\nyes I welcome them too"

In [13]: Levenshtein.matching_blocks([],a,b)
Out[13]: [MatchingBlock(a=0, b=0, size=38), MatchingBlock(a=38, b=63, size=0)]

In [14]: import difflib

In [15]: difflib.SequenceMatcher([],a,b)
Out[15]: <difflib.SequenceMatcher at 0x7fce1f20c400>

In [16]: sm =difflib.SequenceMatcher([],a,b)

In [17]: sm.find_longest_match()
Out[17]: Match(a=0, b=2, size=38)

In [18]: Levenshtein.__version__
Out[18]: '0.21.1'
```

**Comment by maxbachmann** [comment]
Can you add what `a` is? Your transcript only shows the definition of `b`.

**Comment by kpm** [comment]
Sorry about that, it's visible now.

**Comment by maxbachmann** [comment]
Ah that is simply not how `matching_blocks` works. `matching_blocks` is only used to convert from `opcodes` or `editops` to `matching_blocks`. So you would have to use:
```python
> import Levenshtein
> Levenshtein.matching_blocks(Levenshtein.editops(a, b),a,b)
> [MatchingBlock(a=0, b=2, size=38), MatchingBlock(a=38, b=53, size=0)]
```
or in rapidfuzz:
```python
> from rapidfuzz.distance import Levenshtein
> Levenshtein.editops(a, b).as_matching_blocks()
> [MatchingBlock(a=0, b=2, size=38), MatchingBlock(a=38, b=53, size=0)]
```

**Comment by maxbachmann** [comment]
In addition note that `matching_blocks` is not guaranteed to return the same results as difflib. It backtraces the Levenshtein matrix and used one of possibly multiple optimal paths. So depending on you use case it might not be the right tool.

In case you just need to find the longest common subsequence you can use:
```python
> from rapidfuzz.distance import LCSseq
> LCSseq.editops(a, b).as_matching_blocks()
```

Or if your application requires exactly the same output as difflib you can use [cydifflib](https://github.com/maxbachmann/CyDifflib) instead.

**Comment by kpm** [comment]
Yes, I was after the longest common subsequence, but couldn't work out how to do it from the docs.  Thank you for that info.
