### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by AlanApter** [rapidfuzz/python-Levenshtein#5]
The documentation links are broken - both on https://pypi.org/project/python-Levenshtein/ and in the 'about' section on this git repo. They both point to https://maxbachmann.github.io/Levenshtein/ when they should point to https://rapidfuzz.github.io/Levenshtein/

**Comment by AlanApter** [comment]
Specifically in the git repo here:

![image](https://github.com/rapidfuzz/python-Levenshtein/assets/3017506/e703d9d2-2c6c-48b0-abdc-756bc9ba1367)

I can't create a pull request because it's outside the repo, and I'm not sure how to create a pull request for pypi either.

**Comment by maxbachmann** [comment]
Thanks for reporting. Apparently I missed those in the migration.

I fixed this by forwarding the website in https://github.com/maxbachmann/maxbachmann.github.io + updating the links in the about section. I will make a new release for these projects to fix the links on github later today as well, so it contains the appropriate URLs.
