### ISSUE TITLE
Install on kaggle environment

### ISSUE THREAD

**Issue by sondosaabed** [rapidfuzz/python-Levenshtein#8]
Hello!
I am trying to install using this:
`pip install levenshtein` on kaggle notebook
this is the output that I am getting:
Do you have an idea why?
![image](https://github.com/rapidfuzz/python-Levenshtein/assets/65151701/ac8d3092-8eac-490d-b348-84051eb69100)

**Comment by maxbachmann** [comment]
do other installations work? This sounds like a missing internet connection, the dns server being unavailable or something similar.

**Comment by sondosaabed** [comment]
You are right I tried to use pip 
![image](https://github.com/rapidfuzz/python-Levenshtein/assets/65151701/e97350a0-ab1c-4d43-b32a-cd88bbe25546)

Is it from my device you think? I am using firefox

**Comment by sondosaabed** [comment]
Thank you now I know why 
![image](https://github.com/rapidfuzz/python-Levenshtein/assets/65151701/c8af035f-99d5-4ba3-8f87-8b1fb00adf03)
The internet was off in the notebook settings LOL
